from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

from latex_log import FINDING_ORDER, parse_log


ROOT = Path(__file__).resolve().parents[1]
PAPER_DIR = ROOT / "paper"
DOCS_DIR = ROOT / "docs"
PDF_PATH = PAPER_DIR / "main.pdf"
LOG_PATH = PAPER_DIR / "main.log"
REVIEW_PATH = DOCS_DIR / "PDF_REVIEW.md"
TEXT_EXTRACT_PATH = DOCS_DIR / "PDF_TEXT_EXTRACT.md"


def extract_manual_findings(existing_text: str) -> str:
    marker = "## Manual Findings"
    if marker not in existing_text:
        return "- [ ] Read `paper/main.pdf` directly and add page-level issues here."
    return existing_text.split(marker, 1)[1].strip() or "- [ ] Read `paper/main.pdf` directly and add page-level issues here."


def extract_pdf_text(
    pdf_path: Path,
    *,
    max_pages: int | None,
    max_chars: int,
) -> tuple[str, str, int]:
    """Return (status, text, page_count). max_pages None means all pages."""
    if not pdf_path.exists():
        return "missing", "PDF does not exist yet.", 0

    if max_pages is not None and max_pages <= 0:
        max_pages = 1

    try:
        from pypdf import PdfReader  # type: ignore

        reader = PdfReader(str(pdf_path))
        pages = len(reader.pages)
        selected = reader.pages if max_pages is None else reader.pages[:max_pages]
        snippets: list[str] = []
        for page in selected:
            snippets.append((page.extract_text() or "").strip())
        preview = "\n\n--- PAGE BREAK ---\n\n".join(snippets).strip()
        preview = re.sub(r"\n{3,}", "\n\n", preview)
        if max_chars > 0 and len(preview) > max_chars:
            preview = preview[:max_chars] + "\n\n[... truncated; increase --preview-max-chars or use docs/PDF_TEXT_EXTRACT.md ...]"
        method = f"ok via pypdf ({pages} pages"
        if max_pages is not None and pages > max_pages:
            method += f", preview first {max_pages} page(s)"
        method += ")"
        return method, preview or "[no text extracted]", pages
    except Exception:
        pass

    try:
        completed = subprocess.run(
            ["pdftotext", "-layout", str(pdf_path), "-"],
            cwd=ROOT,
            capture_output=True,
            text=True,
            errors="replace",
            check=False,
        )
        if completed.returncode == 0 and completed.stdout.strip():
            text = completed.stdout.strip()
            pages = max(1, text.count("\f") + 1) if "\f" in text else 1
            if max_pages is not None:
                parts = text.split("\f")
                text = "\n\n--- PAGE BREAK ---\n\n".join(parts[:max_pages]).strip()
            if max_chars > 0 and len(text) > max_chars:
                text = text[:max_chars] + "\n\n[... truncated ...]"
            return "ok via pdftotext", text, pages
    except Exception:
        pass

    return (
        "unavailable",
        "No PDF text extractor was available. Install `pypdf` (`pip install pypdf`) or Poppler `pdftotext`, or read `paper/main.pdf` directly in Cursor for render review.",
        0,
    )


def write_full_text_extract(
    pdf_path: Path,
    *,
    max_chars: int,
) -> tuple[str, str, int]:
    """Write full-document text to docs/PDF_TEXT_EXTRACT.md for agent search and diff review."""
    status, body, page_count = extract_pdf_text(pdf_path, max_pages=None, max_chars=0)
    if status == "missing":
        header = [
            "# PDF Text Extract",
            "",
            "_Generated by `scripts/render_audit.py --write-full-extract`._",
            "",
            "`paper/main.pdf` was not found. Build the manuscript first.",
            "",
        ]
        TEXT_EXTRACT_PATH.parent.mkdir(parents=True, exist_ok=True)
        TEXT_EXTRACT_PATH.write_text("\n".join(header), encoding="utf-8")
        return status, "", page_count

    if max_chars > 0 and len(body) > max_chars:
        body = body[:max_chars] + "\n\n[... extract truncated at --extract-max-chars; split the manuscript or raise the limit ...]"

    lines = [
        "# PDF Text Extract",
        "",
        "_Auto-generated for machine review. Extraction order may not match visual reading order; equations and figures may be partial or missing._",
        "",
        f"- Source: `paper/main.pdf`",
        f"- Extraction status: `{status}`",
        f"- Approximate pages: `{page_count}`",
        "",
        "## Full text",
        "",
        "```text",
        body if body.strip() else "[empty]",
        "```",
        "",
    ]
    TEXT_EXTRACT_PATH.parent.mkdir(parents=True, exist_ok=True)
    TEXT_EXTRACT_PATH.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    return status, body, page_count


def build_fix_queue(findings: dict[str, list[str]], pdf_preview_status: str) -> list[str]:
    queue: list[str] = []
    if findings["errors"]:
        queue.append("Resolve LaTeX build errors before any visual cleanup.")
    if findings["missing_files"]:
        queue.append("Restore or remove missing figure, table, or input-file references.")
    if findings["undefined_citations"]:
        queue.append("Fix undefined citations before treating the draft as stable.")
    if findings["undefined_references"]:
        queue.append("Fix undefined cross-references and rerun the build.")
    if findings["overfull_boxes"]:
        queue.append("Inspect pages with overfull boxes for equation overflow, caption spill, or text protrusion.")
    if findings["underfull_boxes"]:
        queue.append("Check for awkward whitespace, bad page breaks, or stretched paragraphs.")
    if pdf_preview_status.startswith("ok"):
        queue.append("Read `paper/main.pdf` directly and cross-check `docs/PDF_TEXT_EXTRACT.md` against page-level layout.")
    else:
        queue.append("Build the PDF successfully before attempting manual render review.")
    return queue


def write_review(
    findings: dict[str, list[str]],
    pdf_preview_status: str,
    pdf_preview_text: str,
    *,
    extract_note: str | None = None,
) -> None:
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    existing = REVIEW_PATH.read_text(encoding="utf-8") if REVIEW_PATH.exists() else ""
    manual_findings = extract_manual_findings(existing)
    fix_queue = build_fix_queue(findings, pdf_preview_status)

    lines: list[str] = [
        "# PDF Review",
        "",
        "This file tracks rendered-PDF issues found after building the manuscript.",
        "",
        "## Artifact Status",
        f"- `paper/main.pdf` present: {'yes' if PDF_PATH.exists() else 'no'}",
        f"- `paper/main.log` present: {'yes' if LOG_PATH.exists() else 'no'}",
        f"- `docs/PDF_TEXT_EXTRACT.md` present: {'yes' if TEXT_EXTRACT_PATH.exists() else 'no'}",
        f"- PDF text preview status: `{pdf_preview_status}`",
    ]
    if extract_note:
        lines.append(f"- Full extract note: {extract_note}")
    lines.extend(
        [
            "",
            "## Automated Findings Summary",
        ]
    )

    for key, label in FINDING_ORDER:
        lines.append(f"- {label}: `{len(findings[key])}`")

    lines.extend(["", "## Automated Findings", ""])

    for key, label in FINDING_ORDER:
        lines.append(f"### {label}")
        if findings[key]:
            lines.extend(f"- [ ] {entry}" for entry in findings[key])
        else:
            lines.append("- [ ] None detected.")
        lines.append("")

    lines.extend(
        [
            "## PDF Text Preview",
            "",
            "This preview is a lightweight sanity check for the first N pages (see `scripts/render_audit.py --help`). It does not replace direct PDF inspection for layout issues. When `docs/PDF_TEXT_EXTRACT.md` exists, use it for full-document text search.",
            "",
            "```text",
            pdf_preview_text,
            "```",
            "",
            "## Direct Visual Review Checklist",
            "",
            "- [ ] No overlapping text blocks",
            "- [ ] No figures cropped, stretched, or off-page",
            "- [ ] No tables extending beyond page margins",
            "- [ ] No equations overflowing into margins",
            "- [ ] No captions colliding with figures or tables",
            "- [ ] No unreadable axis labels, legends, or small fonts",
            "- [ ] No broken page breaks, isolated headings, or giant whitespace gaps",
            "- [ ] No bibliography formatting anomalies",
            "",
            "## Recommended Fix Queue",
            "",
        ]
    )

    lines.extend(f"- [ ] {item}" for item in fix_queue)
    lines.extend(["", "## Manual Findings", "", manual_findings, ""])

    REVIEW_PATH.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Parse main.log and refresh docs/PDF_REVIEW.md (and optional full text extract).")
    parser.add_argument(
        "--preview-pages",
        type=int,
        default=2,
        metavar="N",
        help="Pages to include in the PDF_REVIEW preview (default: 2). Values <= 0 are treated as 1.",
    )
    parser.add_argument(
        "--preview-max-chars",
        type=int,
        default=16000,
        metavar="N",
        help="Maximum characters for the in-review preview (default: 16000).",
    )
    parser.add_argument(
        "--write-full-extract",
        action="store_true",
        help=f"Write full-document text to `{TEXT_EXTRACT_PATH.relative_to(ROOT)}` for agent search and diffing.",
    )
    parser.add_argument(
        "--extract-max-chars",
        type=int,
        default=400_000,
        metavar="N",
        help="Maximum characters for the full extract file (default: 400000).",
    )
    args = parser.parse_args(argv)

    log_text = LOG_PATH.read_text(encoding="utf-8", errors="replace") if LOG_PATH.exists() else ""
    findings = parse_log(log_text)

    max_pages = None if args.preview_pages <= 0 else args.preview_pages
    pdf_preview_status, pdf_preview_text, _pages = extract_pdf_text(
        PDF_PATH,
        max_pages=max_pages,
        max_chars=args.preview_max_chars,
    )

    extract_note: str | None = None
    if args.write_full_extract:
        estatus, _body, pcount = write_full_text_extract(PDF_PATH, max_chars=args.extract_max_chars)
        extract_note = f"`{TEXT_EXTRACT_PATH.name}` refreshed ({estatus}, ~{pcount} pages)."

    write_review(findings, pdf_preview_status, pdf_preview_text, extract_note=extract_note)
    print("Updated docs/PDF_REVIEW.md")
    if args.write_full_extract:
        print(f"Updated {TEXT_EXTRACT_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
